# Generated by Django 5.1.1 on 2026-03-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='timeline',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
