# Generated by Django 5.1.1 on 2026-02-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_blog_highlights_alter_blog_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='blog',
            name='highlights_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='blog',
            name='images_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='experience',
            name='achievements_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack_json',
            field=models.TextField(blank=True),
        ),
    ]
